---
version: 3

images:
  base_image:
    name: artifactory.platform.aib.pri/remote-registry-redhat/ansible-automation-platform-24/ee-minimal-rhel9:latest

dependencies:
  python_interpreter:
    package_system: python3
  ansible_core:
    package_pip: ansible-core==2.15
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - community.general
  # python:
  system:
    - sshpass [platform:redhat]
    - git [platform:redhat]
    - unzip [platform:redhat]
    - glibc-langpack-en [platform:redhat]
    - glibc-locale-source [platform:redhat]

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: files/*
    dest: configs

additional_build_steps:
  prepend_galaxy: |
    ADD _build/configs/*.crt /etc/pki/ca-trust/source/anchors/
    RUN update-ca-trust
    ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub
    ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL
    ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN

  prepend_base: |
    ADD _build/configs/*.crt /etc/pki/ca-trust/source/anchors/
    ADD _build/configs/*.repo /etc/yum.repos.d/
    RUN update-ca-trust
    RUN pip3 config set global.trusted-host "artifactory.platform.aib.pri"
    RUN pip3 config set global.index-url "https://artifactory.platform.aib.pri/api/pypi/remote-pypi/simple"
    RUN pip3 install --upgrade pip setuptools

  prepend_builder: |
    ADD _build/configs/*.crt /etc/pki/ca-trust/source/anchors/
    RUN update-ca-trust
    RUN pip3 config set global.trusted-host "artifactory.platform.aib.pri"
    RUN pip3 config set global.index-url "https://artifactory.platform.aib.pri/api/pypi/remote-pypi/simple"

  append_final:
    - RUN localedef -i en_GB -f UTF-8 en_GB.UTF-8
    - ENV LANG=en_GB.UTF-8
    - ENV LANGUAGE=en_GB.utf8
    - ENV TZ=Europe/Dublin
    - ENV HISTTIMEFORMAT="%Y-%m-%d_%H:%M:%S "
    - ENV LC_TIME=en_GB.UTF-8
    - ENV LC_NUMERIC=en_GB.UTF-8
    - ENV LC_ALL=en_GB.UTF-8
    - RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    - RUN $PKGMGR clean all
